# Netlify Configuration for HealthyThako Production Deployment
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Payment redirect handler - CRITICAL for payment processing
[[redirects]]
  from = "/payment-redirect"
  to = "/payment-redirect/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/payment-redirect/*"
  to = "/payment-redirect/index.html"
  status = 200
  force = true

# SPA routing - serve index.html for all routes (except payment-redirect)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# API redirects to Supabase
[[redirects]]
  from = "/api/*"
  to = "https://lhncpcsniuxnrmabbkmr.supabase.co/rest/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://lhncpcsniuxnrmabbkmr.supabase.co/auth/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/functions/*"
  to = "https://lhncpcsniuxnrmabbkmr.supabase.co/functions/v1/:splat"
  status = 200
  force = true

# Headers for proper MIME types
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Payment redirect handler security headers
[[headers]]
  for = "/payment-redirect/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # CORS headers for Supabase integration
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, apikey"
    # Content Security Policy for payment redirect
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com https://cdn.jsdelivr.net; connect-src 'self' https://lhncpcsniuxnrmabbkmr.supabase.co; style-src 'self' 'unsafe-inline';"